[PSL-1110][PSL-1113][PSL-1160][PSL-1161][PSL-1162][PSL-1163][PSL-1165][PSL-1166]
[PSL-1110] Change `masternode start-alias` to `masternode activate`
- changed pasteld RPC APIs:
    masternode start-alias    ==> masternode activate
	masternode start-all      ==> masternode activate-all
	masternode start-disabled ==> masternode activate-disabled
	masternode start-missing  ==> masternode activate-missing
Old APIs still work for backward compatibility, but RPC API help has changed to reflect new changes.

[PSL-1113] pasteld should automatically create the pastelkeys directory when it first launches, even if the user doesn't have any pastel ids yet
- automatically create pastelkeys directory on pasteld startup if it does not exist

[PSL-1160]
pasteld is checking all new v5 blocks mined within last 30 mins:
 - pasteld specified in the block belongs to the masternode (mind)
 - checking signature for the merkle root of the previous block
 - MN outpoint was not spent
 - checking that MN was eligible to mine this block (if 6 mins passed since last block then all ENABLED MNs will be eligible to mine that block)

changes:
 - skip MN eligibility checks if MasterNode list is not synced yet.
 - improved logging for the case MN is not eligible to mine the block being checked:
    - added block time
	- added last mined block height

[PSL-1161] pasteld: suppress 'unknown transaction type found' log message for tickets

[CWalletTx::GetAmounts] Unknown transaction type found, txid 'd9b10f2d845c7879b621007565ea8720675ddc3cc5969c964e4d53bc3863ee3a', out #0
Suppress these log messages for P2FMS ticket multisig transactions when input address is stored in the local wallet.
One example of these tickets is mnid registration ticket.

[PSL-1162] pasteld: scanburntransactions RPC API
Implemented new RPC API to scan blockchain for the burn transactions:
scanburntransactions "from_taddress" ( hash|height )
Scan for the transactions from the given taddress to the burn address.

Arguments:
1. "from_taddress" (string, required) The transparent address that the transactions are sent from.
                   If '*' is given, will scan for transactions from all addresses.
2. hash|height     (string or numeric, optional) The block hash or height to start scanning from.
                   If not provided, the scan starts from the genesis block.

Result:
[
  {
	 "txid": "hashvalue", 	   (string)  The transaction id
	 "blockhash": "hashvalue", (string)  The hash of the block containing the transaction
	 "blockindex": n,          (numeric) The height of the block containing the transaction
     "timestamp": nnn,         (numeric) The timestamp of the block containing the transaction
     "from_address": "xxx",    (string)  The transparent address that the transaction is sent from
     "confirmations": n,       (numeric) The number of confirmations of the block containing the transaction
	 "amount": nnn,            (numeric) The amount of the transaction in PSL
	 "amountPat": nnn          (numeric) The amount of the transaction in patoshis
  },
  ...
]

If starting block hash or block height is specified as a last parameter - this API will start scanning from that block only. Otherwise it will scan from the genesis block.
Scan memory pool for burn transactions as well. If burn transaction was found in the mempool - it will be reported with blockhash='NA', blockindex=0, confirmations=0, timestamp=0.
Implemented common CBlockScanner class to support multithreaded blockchain scanning from the specified block.
This does not require cs_main lock to be locked all the time. It starts by collecting all info for the blocks it needs to scan (block file no + file position). Then it split the work into multiple threads, where each thread reads specified block from the disk and executes some specific code (like scanning for the burn transactions).
Used CBlockScanner class also for the get-total-coin-supply RPC API.

[PSL-1163] pasteld: getblockmininginfo enhancement
Changed getblockmininginfo RPC API to include ability to filter results by masternode collateral id or mnid.
getblockmininginfo "block_hash|block_height" (block_count) (filter)
Returns information about blocks mined and signed by masternodes.

 Arguments:
 1. "block_hash|block_height"   (string or numeric, required) The block hash or height to start from
 2. block_count                 (numeric, optional, default=1) The number of blocks to return backwards
 3. filter                      (string, optional) filter results by masternode collateral id (txid-vout) or mnid

[PSL-1164] pasteld: storagefee setfee fix
storagefee setfee RCP API returns an error when called from pastel-cli:
  error: Error parsing JSON:storage
Fixed parsing parameters in pastel-cli for the "storagefee setfee".

[PSL-1165] pasteld: getblockhash RPC API enhancement
Enhanced getblockhash RPC API to define block count optional parameter.
getblockhash height ( count )
Returns hashes of blocks in best-block-chain at the heights range provided.
Returns hashes of blocks in best-block-chain at the heights range provided.

Arguments:
1. height (numeric, required) The starting block height
2. count  (numeric, optional) Number of block hashes to return. Default is 1.
                              -1: all blocks up to the current tip
Result (no "count" parameter):
  "hash"  (string) The block hash

Result (with "count" parameter):
[		   (json array of objects)
  {
	"height": n,    (numeric) The block height
	"hash": "xxxxx" (string) The block hash
  },
  ...
]

[PSL-1166] pasteld: contract ticket
Implemented new ticket type - contract:
"ticket": {
		"type": "contract",       // Contract ticket type
        "version": int,           // ticket version (1)
        "sub_type": string,       // ticket sub-type
        "secondary_key": string,  // ticket secondary key
		"contract_ticket": bytes, // contract ticket data
	}
primary key is generated to be unique, cannot be defined via "tickets register" API.
secondary_key is optional secondary key, can be defived via "tickets register".
sub_type - contract ticket sub-type (required field, used as a secondary index).
contract_ticket is an extrernal base64-encoded data as a string.
contract_ticket data can be in json or binary format.

New RPC APIs for contract tickets:
1) tickets register contract "{contract-ticket}" "subtype" ["secondary_key"] ["address"]
Register new contract ticket. If successful, method returns "txid".
Arguments:
1. "{contract-ticket}"	(string, required) Base64 encoded contract ticket (binary or json).
2. "subtype"			(string, required) Contract ticket subtype.
3. "secondary_key"		(string, optional) Secondary key for the contract ticket.
4. "address"			(string, optional) The Pastel blockchain t-address to use for funding the registration.

2) tickets get txid [decode_properties]
Returns ticket JSON. If decode_properties=true(1) and contract_ticket is valid JSON, it will be
returned in the output as well.

3) tickets find contract "key"
Find contract ticket(s) by "key".
The "key" is 'Primary generated key' OR 'ticket sub type' OR 'secondary key'

4) tickets list contract ("filter") ("minheight")
List contract tickets.
Filter:
  all       - lists all contract tickets. Default.
  "subtype" - lists only contract tickets of the specified subtype.

5) tickets findbylabel contract "label"
Find contract ticket by secondary key.

Implemented python tests for contract tickets that covers:
 - registration API
 - contract ticket validation
 - tickets get/find/list/findbylabel APIs